# Generated by Django 5.2.8 on 2025-11-19 17:49

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Qrcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=12, unique=True, validators=[django.core.validators.MinLengthValidator(8)])),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_used', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('middle_name', models.CharField(blank=True, max_length=20)),
                ('phone_number', models.CharField(max_length=20)),
                ('telegram_username', models.CharField(blank=True, max_length=50)),
                ('direction', models.CharField(choices=[('rfutbol', 'Robo Futbol'), ('rsumo', 'Robo sumo'), ('fixtirolar', 'Foydali Ixtirolar')], max_length=20)),
                ('birth_date', models.DateField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('study_place', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('about', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('qr_code', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.qrcode')),
            ],
        ),
    ]
