# Generated by Django 5.2.8 on 2025-11-20 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AddField(
            model_name='user',
            name='friend',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='friends', to='main.user', verbose_name="Do'st (Robo Futbol uchun)"),
        ),
        migrations.AddField(
            model_name='user',
            name='is_friend',
            field=models.BooleanField(default=False, verbose_name="Do'st bilan ishtirok etadi"),
        ),
    ]
